CLASS zcl_account_status_manager DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR EVENTS OF ZR_BankAccountTP.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_account_status_manager IMPLEMENTATION.
ENDCLASS.
